### PR TITLE
Add files via upload

### PR DESCRIPTION
**Pull request by Kozlov-Sergey-Aleksandrovitch**

### CODE REVIEW

**Comment by Kozlov-Sergey-Aleksandrovitch** [comment]
Error. New in this bussiness.

**Comment by Zerbinati** [comment]
This branch has conflicts that must be resolved.Use the command line to
resolve conflicts before continuing.

Il 06 ott 2017 12:19 AM, "Kozlov Sergey Aleksandrovitch" <
notifications@github.com> ha scritto:

**Comment by Kozlov-Sergey-Aleksandrovitch** [comment]
You can load from my fork.
In your fork only you can resolve, because only you have got write access right.

**Comment by Kozlov-Sergey-Aleksandrovitch** [comment]
Can you remove
srcS/main.cpp
srcS/tt.cpp

and load from my fork from
source/main.cpp
source/tt.cpp

?

**Pull request merged**
